//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcamViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebcamViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webcam Viewer.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SETTINGS.
        /// </summary>
        public static string Settings_UpperCase {
            get {
                return ResourceManager.GetString("Settings_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About &amp; updates.
        /// </summary>
        public static string settingsPage_AboutAndUpdates {
            get {
                return ResourceManager.GetString("settingsPage_AboutAndUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Debug settings.
        /// </summary>
        public static string settingsPage_DebugSettings {
            get {
                return ResourceManager.GetString("settingsPage_DebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default customizations debug.
        /// </summary>
        public static string settingsPage_DefaultCustomizationsDebug {
            get {
                return ResourceManager.GetString("settingsPage_DefaultCustomizationsDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string settingsPage_Home {
            get {
                return ResourceManager.GetString("settingsPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User interface.
        /// </summary>
        public static string settingsPage_UserInterface {
            get {
                return ResourceManager.GetString("settingsPage_UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Webcams.
        /// </summary>
        public static string settingsPage_Webcams {
            get {
                return ResourceManager.GetString("settingsPage_Webcams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Try again.
        /// </summary>
        public static string Try_again {
            get {
                return ResourceManager.GetString("Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving to archive.org....
        /// </summary>
        public static string webcamPage_ArchiveOrgProgress {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved!.
        /// </summary>
        public static string webcamPage_ArchiveOrgProgressFinished {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save on archive.org.
        /// </summary>
        public static string webcamPage_ArchiveOrgSave {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save image.
        /// </summary>
        public static string webcamPage_LocalSave {
            get {
                return ResourceManager.GetString("webcamPage_LocalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading image: .
        /// </summary>
        public static string webcamPage_LocalSaveProgress {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saved!.
        /// </summary>
        public static string webcamPage_LocalSaveProgressFinished {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preparing to save image....
        /// </summary>
        public static string webcamPage_LocalSaveProgressPreparing {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgressPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Overview.
        /// </summary>
        public static string webcamPage_Overview {
            get {
                return ResourceManager.GetString("webcamPage_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to camera view.
        /// </summary>
        public static string webcamPage_OverviewGoBack {
            get {
                return ResourceManager.GetString("webcamPage_OverviewGoBack", resourceCulture);
            }
        }
    }
}
