//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcamViewer.Updates.Updates.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebcamViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam Viewer.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings_UpperCase {
            get {
                return ResourceManager.GetString("Settings_UpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &amp; updates.
        /// </summary>
        public static string settingsPage_AboutAndUpdates {
            get {
                return ResourceManager.GetString("settingsPage_AboutAndUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug settings.
        /// </summary>
        public static string settingsPage_DebugSettings {
            get {
                return ResourceManager.GetString("settingsPage_DebugSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default customizations debug.
        /// </summary>
        public static string settingsPage_DefaultCustomizationsDebug {
            get {
                return ResourceManager.GetString("settingsPage_DefaultCustomizationsDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera settings.
        /// </summary>
        public static string settingsPage_Home {
            get {
                return ResourceManager.GetString("settingsPage_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string settingsPage_UserInterface {
            get {
                return ResourceManager.GetString("settingsPage_UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcams.
        /// </summary>
        public static string settingsPage_Webcams {
            get {
                return ResourceManager.GetString("settingsPage_Webcams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string Try_again {
            get {
                return ResourceManager.GetString("Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving to archive.org....
        /// </summary>
        public static string webcamPage_ArchiveOrgProgress {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string webcamPage_ArchiveOrgProgressFinished {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save on archive.org.
        /// </summary>
        public static string webcamPage_ArchiveOrgSave {
            get {
                return ResourceManager.GetString("webcamPage_ArchiveOrgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image.
        /// </summary>
        public static string webcamPage_LocalSave {
            get {
                return ResourceManager.GetString("webcamPage_LocalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading image: .
        /// </summary>
        public static string webcamPage_LocalSaveProgress {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string webcamPage_LocalSaveProgressFinished {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to save image....
        /// </summary>
        public static string webcamPage_LocalSaveProgressPreparing {
            get {
                return ResourceManager.GetString("webcamPage_LocalSaveProgressPreparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string webcamPage_Overview {
            get {
                return ResourceManager.GetString("webcamPage_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to camera view.
        /// </summary>
        public static string webcamPage_OverviewGoBack {
            get {
                return ResourceManager.GetString("webcamPage_OverviewGoBack", resourceCulture);
            }
        }
    }
}
