//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcamViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Michalovce - Námestie osloboditeľov 01 [SK]</string>
  <string>Nowy Targ - Ugazdy - Kamera na Tatry [PL]</string>
  <string>Glavmore (Camera 2) [RU]</string>
  <string>Poprad - Funsat Meteo [SK]</string>
  <string>Michalovce - Busová stanica (gecom.sk) [SK]</string>
  <string>Zywiec - Zywiec Lake (megasurf.pl) [PL]</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection camera_names {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["camera_names"]));
            }
            set {
                this["camera_names"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://www.michalovce.sk/webcam/michalovce.sk-camera-001.jpg</string>
  <string>http://www.ugazdy.pl/kamerka/obrazek.jpg</string>
  <string>http://static.glavmore.ru/cam/cam-1.jpg</string>
  <string>http://funsat.sk.d.websupport.sk/webcam/funsat.jpg</string>
  <string>http://gecom.sk/img/autobuska-aktualne.jpg</string>
  <string>http://www.megasurf.pl/cam/Video01.jpg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection camera_urls {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["camera_urls"]));
            }
            set {
                this["camera_urls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20160714-01")]
        public string buildid {
            get {
                return ((string)(this["buildid"]));
            }
            set {
                this["buildid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Changes for 20160714-01:

  Fixes:
- Fixed the big buttons on the Settings page to look more like the ones in Windows 10's
Settings app.
- Fixed the webcam editor page's Save changes button to use the UWP button style.
- Fixed a bug where exiting Settings would not reload your configuration, so the app
would infinitely load. Now, whenever you exit out of Settings, all your configuration gets
reloaded, applying any changes you've made.

  Improvements:
- Added an additional Settings page ""User interface"".
- Added a toggle for blurring the webcam image when action is happening
  This applies for saving the image and will apply to other features in the future.
  The blur can impact performance on lower-end computers, turning it off should reduce 
lag when saving the image.
- Reduced the accent color on light dialogs for better visibility.

  New features:
- There are 4 new command line arguments you can use:

  | -readonly
  | Disables the save buttons.
  
  | -disable_archive
  | Disables the archive.org save button, along with the ""save all"" button.

  | -disable_localsave
  | Disables the local save button, along with the ""save all"" button.

  | -disable_webcameditor
  | Disables the webcam editor in Settings.

  You are notified when any of them is active on the Settings page.

  Additionally, Webcam Viewer has a webpage: xezrunner.github.io/WebcamViewer.
")]
        public string changelog {
            get {
                return ((string)(this["changelog"]));
            }
            set {
                this["changelog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool birthday_notice {
            get {
                return ((bool)(this["birthday_notice"]));
            }
            set {
                this["birthday_notice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool blur_image {
            get {
                return ((bool)(this["blur_image"]));
            }
            set {
                this["blur_image"] = value;
            }
        }
    }
}
