//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebcamViewer.Updates.Updates.Pages.Settings_page.Subpages._1_Home.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebcamViewer.Pages.Settings_page.Subpages._1_Home.res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to archive.org integration.
        /// </summary>
        public static string ArchiveOrgIntegration {
            get {
                return ResourceManager.GetString("ArchiveOrgIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable the archive.org save button.
        /// </summary>
        public static string ArchiveOrgIntegration_Description {
            get {
                return ResourceManager.GetString("ArchiveOrgIntegration_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable autorefresh.
        /// </summary>
        public static string Autorefresh {
            get {
                return ResourceManager.GetString("Autorefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globally enable or disable automatically refreshing the image..
        /// </summary>
        public static string Autorefresh_Description {
            get {
                return ResourceManager.GetString("Autorefresh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image sizing.
        /// </summary>
        public static string ImageSizing {
            get {
                return ResourceManager.GetString("ImageSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how the image should be displayed in the window...
        ///Current setting: .
        /// </summary>
        public static string ImageSizingDescription {
            get {
                return ResourceManager.GetString("ImageSizingDescription", resourceCulture);
            }
        }
    }
}
